# Generated by Django 5.2.1 on 2025-05-22 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpireToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('expire', models.DateField()),
            ],
            bases=('authtoken.token',),
        ),
    ]
