# Generated by Django 5.2.1 on 2025-05-22 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_expiretoken_expire'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('expire', models.DateTimeField(default=datetime.datetime(2025, 5, 22, 12, 13, 56, 802008, tzinfo=datetime.timezone.utc))),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='expiretoken',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 22, 12, 13, 56, 800985, tzinfo=datetime.timezone.utc)),
        ),
    ]
