# Generated by Django 5.2.1 on 2025-05-23 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_otp_alter_expiretoken_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiretoken',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 23, 8, 24, 41, 427001, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 23, 8, 24, 41, 427770, tzinfo=datetime.timezone.utc)),
        ),
    ]
