# Generated by Django 5.2.1 on 2025-06-02 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_expiretoken_expire_alter_otp_expire_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiretoken',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 5, 6, 48, 344298, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 5, 6, 48, 345529, tzinfo=datetime.timezone.utc)),
        ),
    ]
